# Generated by Django 5.0.3 on 2024-03-30 17:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('ArtistID', models.AutoField(primary_key=True, serialize=False)),
                ('ArtistName', models.CharField(max_length=100)),
                ('Bio', models.TextField()),
                ('Hometown', models.CharField(max_length=100)),
                ('BirthDate', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
                ('Thumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('PaymentInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('AlbumID', models.AutoField(primary_key=True, serialize=False)),
                ('AlbumName', models.CharField(max_length=200)),
                ('NumberOfSongs', models.IntegerField()),
                ('Length', models.DurationField()),
                ('ReleaseDate', models.DateField()),
                ('Description', models.TextField()),
                ('Genre', models.CharField(max_length=100)),
                ('Thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('ArtistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('SongID', models.AutoField(primary_key=True, serialize=False)),
                ('SongName', models.CharField(max_length=200)),
                ('Length', models.DurationField()),
                ('Genre', models.CharField(max_length=100)),
                ('ReleaseDate', models.DateField()),
                ('Streams', models.IntegerField()),
                ('Thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('AlbumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.album')),
                ('ArtistID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
            ],
        ),
    ]
