# Generated by Django 5.0.3 on 2024-04-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_genre_album_genre_alter_artist_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='totalStreams',
            field=models.IntegerField(default=0),
        ),
    ]
