# Generated by Django 5.0.3 on 2024-04-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_artist_totalstreams'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='averageStreams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='totalStreams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='averageStreams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='averageStreams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='totalStreams',
            field=models.IntegerField(default=0),
        ),
    ]
