# Generated by Django 5.0.3 on 2024-04-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_album_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='listener',
            name='listenerName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='LikeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listener')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.song')),
            ],
        ),
        migrations.AddConstraint(
            model_name='likeinteraction',
            constraint=models.UniqueConstraint(fields=('listener', 'song', 'date'), name='unique_like'),
        ),
    ]
